//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSERTIFIKALAR
    {
        public int ID { get; set; }
        public string SERTIFIKALARIM { get; set; }
        public string KURUM { get; set; }
        public string EĞİTMEN { get; set; }
        public string TARİH { get; set; }
        public string SÜRE { get; set; }
    }
}
